# Generated by Django 4.2.5 on 2023-09-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentTitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('uploadDate', models.DateField()),
                ('totalViews', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('enrollmentCapacity', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.category', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('verificationStatus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='QuizQAndA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizQuestion', models.CharField(max_length=200)),
                ('quizAnswer', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=200)),
                ('optionB', models.CharField(max_length=200)),
                ('optionC', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'QuizQandA',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('verificationStatus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabusTitle', models.CharField(max_length=100)),
                ('topic', models.TextField()),
                ('chapters', models.CharField(max_length=100)),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Syllabus',
            },
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('maxScore', models.IntegerField()),
                ('userScore', models.IntegerField()),
                ('time', models.TimeField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.course', verbose_name='Coure')),
                ('fk_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.instructor', verbose_name='Intructor')),
                ('fk_quizQAndAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.quizqanda', verbose_name='Answer')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('uploadDate', models.DateField()),
                ('fk_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.content', verbose_name='content')),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.course', verbose_name='Course')),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.student', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Faq',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentDate', models.DateField()),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.course', verbose_name='Course')),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.student', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Enrollment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='fk_intructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.instructor', verbose_name='Intructor'),
        ),
        migrations.AddField(
            model_name='content',
            name='fk_intructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='content',
            name='fk_syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.syllabus', verbose_name='Sallabus'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classTitle', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('classDate', models.DateField()),
                ('classTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.course', verbose_name='Course')),
                ('fk_nstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name_plural': 'Class Schedule',
            },
        ),
    ]
